name: kicad

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  kicad:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: ./kicad_fluxense/fluxense.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
